### ISSUE TITLE
NoMethodError: undefined method `synchronize' for nil:NilClass

### ISSUE THREAD

**Issue by phlegx** [RubyMoney/eu_central_bank#40]
If I use the gem with version ```0.4.0``` with rails  ```4.2.3``` and ruby ```2.2.2``` I get the following error:

```
irb> eu_bank = EuCentralBank.new
irb> eu_bank.update_rates
irb> NoMethodError: undefined method `synchronize' for nil:NilClass
        from /bundler/gems/eu_central_bank-6038f21813e8/lib/eu_central_bank.rb:98:in `update_parsed_rates'
        from /bundler/gems/eu_central_bank-6038f21813e8/lib/eu_central_bank.rb:19:in `update_rates'
```

**The variable ```@mutex``` seams to be nil! Any idea?**

**Comment by takiy33** [comment]
Thank you for opening issue. I can not reproduce this error.
I get below message when I exexute `bundle install`.

```
naiad% bundle install
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
Bundler could not find compatible versions for gem "i18n":
  In Gemfile:
    rails (= 4.2.3) ruby depends on
      activejob (= 4.2.3) ruby depends on
        activesupport (= 4.2.3) ruby depends on
          i18n (~> 0.7) ruby

    eu_central_bank (= 0.4.0) ruby depends on
      money (~> 6.3.0) ruby depends on
        i18n (<= 0.7.0.dev, >= 0.6.4) ruby
```

**Comment by inyigo** [comment]
getting same error for rails `4.2.3`

```
[6] pry(main)> eu_bank.update_rates      
NoMethodError: undefined method `synchronize' for nil:NilClass
from /Users/inyigo/.rvm/gems/ruby-2.2.2@hkakabo/gems/eu_central_bank-0.3.8/lib/eu_central_bank.rb:69:in `update_parsed_rates'
```

**Comment by FunkyloverOne** [comment]
hello, to reproduce this error you got to use money gem of version "~> 6.6.0", i have got it when was rewriting this gem National Bank of Ukraine

**Comment by semmons99** [comment]
Please submit a PR with a minimal failing test.
